### ISSUE TITLE
Build failed: BuildError: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive JOBS=MAX npm install --unsafe-perm --loglevel error' returned a non-zero code: 8

### ISSUE THREAD

**Issue by FRVisser** [resin-io-projects/beaglebone-adc-node#2]
This is on beaglebone:

```
Step 5 : RUN DEBIAN_FRONTEND=noninteractive JOBS=MAX npm install --unsafe-perm --loglevel error
 ---> Running in c7d7f63f0bc9

/usr/local/lib/node_modules/npm/node_modules/npmconf/config-defs.js:320
  Object.keys(os.networkInterfaces()).map(function (nic) {
                 ^
Error: UNKNOWN, unknown error
    at getLocalAddresses (/usr/local/lib/node_modules/npm/node_modules/npmconf/config-defs.js:320:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmconf/config-defs.js:268:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmconf/npmconf.js:4:18)
    at Module._compile (module.js:456:26)
Removing intermediate container c7d7f63f0bc9
Build failed: BuildError: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive JOBS=MAX npm install --unsafe-perm --loglevel error' returned a non-zero code: 8
```

**Comment by shaunmulligan** [comment]
@FRVisser are you still hitting this issue? I updated the base image and node version for this project and I don't get any build errors, could you give it a retest?

**Comment by FRVisser** [comment]
Let's close this one after a year. Although npm gives a lot warnings, it now builds fine, thanks.
